### ISSUE TITLE
How can i get the ~ symbol and keep my theme(panda-theme)

### ISSUE THREAD

**Issue by gerald-lbn** [benavern/cmder_custom#2]
How can i keep the title( picture 1) to work and remove the blue rectangle(picture 2)?
![image](https://user-images.githubusercontent.com/36128190/80189482-04b9af80-8613-11ea-8eb4-a7d465c4168a.png)

![image](https://user-images.githubusercontent.com/36128190/80189988-d5f00900-8613-11ea-96e3-9191f2f824b7.png)

**Comment by benavern** [comment]
Hi, you could just copy the `tilde.lua` file instead of all the lua files.

**Comment by benavern** [comment]
OK, I just understood what you are trying to do, it's about the `cwd` part of the prompt.
I'm sorry but I don't use windows anymore so can't try anything but if you are comfortable with code, you could try to make your own `theme.lua` file with only the `lambda_prompt_filter` function

My guess would be something like: 

```lua
-- I want to pass it from a function to an other...
local env

-- Resets the prompt 
function lambda_prompt_filter()
    local cwd = clink.get_cwd()
    cwd = string.gsub(cwd, clink.get_env("home"), "~")

    env = clink.prompt.value:match('%[33;22;49m%((.+)%).+%[39;22;49m')
    
    local prompt = "\x1b[1;32;40m{cwd} {git}{hg}{svn} \n\x1b[1;39;40m{lamb} \x1b[0m"
    local new_value = string.gsub(prompt, "{cwd}", cwd)
    local lambda = "λ"
    clink.prompt.value = string.gsub(new_value, "{lamb}", lambda)
end

-- override the built-in filters
clink.prompt.register_filter(lambda_prompt_filter, 55)

```

**Comment by gerald-lbn** [comment]
Thanks for your quick reply, that was exactly what I want.
